INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte barra tensor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do friso do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da grade dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da calha do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento lateral da coroa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Impermeabilizador de tecidos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Travessa do radiador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento do alternador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bigode de lata');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Assoalho da bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da lanterna traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Purificador de Ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha rosca do batente');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Carregador de bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Atuador de marcha lenta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Assoalho da mala');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit de embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor lambda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna do revestimento porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha da grade');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porta copo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento externo retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do revestimento da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limitador de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grade da coluna da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Assento cadeirinha automotiva');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aplique do tapete');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo da fechadura');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Centralina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Massa de calafetar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Junta de carter');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa organizadora');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Arruela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Comutador de partida');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chupeta de bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave L');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Moldura da placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pestana externa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa do retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor do vidro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha da bandeja');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha do grampo do spoiler');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rack transversal');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Balancim');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte da placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo da embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 14 Ford');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna auxiliar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da haste da fechadura');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Arruela para calota');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Massa de polir');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conector adaptador para radio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Spoiler traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do friso do estribo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa de pedal');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna da placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porta CD');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte do vidro da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Remendo painel traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Emblema');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Difusor de roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 15');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa da haste do limpador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 14 Chevrolet');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tapa furo do pneu');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa de acionamento da chave');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento diferencial');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Subwoofer');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cera');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da janela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Distribuidor T');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpa radiador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lixa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave saca pino de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo da tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do carpete');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave estrela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Graxa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Brilho final');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sirene para alarme');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Estopa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capacete');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit do amortecedor traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Parafuso da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Amortecedor traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rele do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa parafuso Revestimento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Receptor automotivo para TV');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpa pneu');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rotor do distribuidor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Remendo da caixa de estepe');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Elimina riscos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Painel de instrumento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha superior da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave do limpador do vidro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa de parafuso');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Adesivo refletor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grade lateral fixa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chapinha do aro do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rebitadeira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Papel para polimento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Remendo do assoalho');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento do suporte do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Revestimento lateral traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Disco de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 13');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa externa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Radiador do motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpador do vidro traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aplique da grade');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Console');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota do centro da roda VW');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Desodorante');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota do centro da roda Fiat');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit cristalizador para autos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aplique aro do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Manopla que levanta o banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha da churrasqueira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Alavanca de regulagem do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpador do vigia com haste');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso colante');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do aro do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Buzina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Terminal de encaixe');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porca do estepe');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Adesivo coluna da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpa vidros');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lateral traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpa couro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tampa do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Woofer');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento interno vidro traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pedaleira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor do retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porca da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente do retrovisor com base');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rele de buzina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Antena');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Correia com perfil em V');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo do acelerador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Painel dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 15 Chevrolet');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol de socorro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Giroflex 12v com ima');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa do volante');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do revestimento lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cubo de roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soquete do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpa carter');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grade dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Organizador automotivo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Maquina para massa de mastic');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente da fechadura da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Roldana do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Controle para alarme');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente da lanterna traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Luva para lavar carro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acendedor de cigarros');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa para ferramentas');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Remendo de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso do estribo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor de estacionamento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aro do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sealed bean');
INSERT INTO maintenance_parts_list (part_name) VALUES ('CD player');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aplique capa do retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bandeja da bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa protetora');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coxim do radiador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Remendo lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 13 Chevrolet');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tampa do reboque');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Adesivo de coluna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cruzeta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro da chave da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Alarme para motos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Saia dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo acabamento retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Moldura do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit para lavar carro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da pestana');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento apoio da correia');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bomba para calibrar pneus');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soquete da lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Assoalho');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bronzina de mancal');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porta celular');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soquete da lanterna traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bloqueador automatico');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente lanterna da placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna dianteira tuning');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Silicone');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Terminal adaptador de antena');
INSERT INTO maintenance_parts_list (part_name) VALUES ('DVD player');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Celuloide para aplicar massa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aro da lanterna traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento tensor da correia');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aplique da soleira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tapete de borracha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota do centro da roda Ford');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit rolamento roda dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cubo para volante');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Letreiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conjunto de cabo de vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conjunto de vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo de vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit junta do motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Saia traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Entrada de ar do painel');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aditivo para radiador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soquete da lanterna de placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Adesivo com leds');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro da chave do contato');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cavalete');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Ventilador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota do centro da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Faixa adesiva');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Espanador de poeira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Restaurador de couro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da grade');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor ventilador do ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente do retrovisor sem base');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Retentor traseiro virabrequim');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Spot mini');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calha de chuva');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa para banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Moldura da grade');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rebite');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cobertura da lanterna de placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Volante');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tampinha do furo da antena');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Painel traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Porta bagagem para rack');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Xampu');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa de estepe');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte para bicicleta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aro da lanterna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit de farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Engate');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota aro 14');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha crua');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Antena do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave de roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Macaco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol tuning');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso do farol de milha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha da tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Protetor de porta removivel');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit para encerar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Corneta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Refil do limpador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa interna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Saca pino da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do spoiler lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pino da trava da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento da saia dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabide da coluna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Entrada de ar lateral externa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Polidor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit rolamento da roda traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soquete da lanterna do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tampa para furo do assoalho');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha interruptor de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do revestimento do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa de carro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do friso da soleira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Spoiler lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Massa KPO');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa para motos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tensor da correia');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha do vidro traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit do amortecedor dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cinta para rack');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro de ar do motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Manopla de regulagem do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Canaleta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha pino de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Aro do quebra vento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Platinado');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente da lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Protetor da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Massa poliester');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Toalha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Espelho olho de boi');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Boina para polimento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lava auto a seco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do friso lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pneu');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tapete tuning');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Alavanca da chave de seta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Travessa do painel dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Moldura do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo suporte do bagagito');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte do extintor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coxim do escapamento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Amortecedor dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tubo do escape');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Arremate do vidro porta traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da saia dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Gel de glicerina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave de fenda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cristalizador de vidros');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tampa do distribuidor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pestana interna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Limpador de ar condicionado');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do fio da vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bolsa da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna para socorro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Folha de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calota do centro da roda GM');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Soleira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da borracha da saia');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Haste do limpador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento do vidro traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Haste da antena do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro mestre do freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Esponja');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabo do afogador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Moldura da lanterna dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Suporte para encaixe da chave');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna de teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha da janela lateral traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Mangueira do filtro de ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Base da lente do retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Estribo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo de cabos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Retrovisor externo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cadeirinha automotiva');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Quadro do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Monitor com tela de LCD');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Regulador de voltagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pastilha de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Faixa branca do pneu');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fechadura da porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Retrovisor interno');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento da coluna interna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pedal do acelerador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave combinada');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Disco de borracha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Revestimento de porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave de vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Arame de solda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Retentor dianteiro virabrequim');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna traseira tuning');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa para motociclista');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Acabamento do friso lateral');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pistola para cola de silicone');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bronzina da biela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conjunto de bielas');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conjunto de pistões');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Pistão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Feltro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa de som');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Spoiler dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa parafuso da roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Churrasqueira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Borracha entre os vidros laterais');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa regulagem do banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Olho de gato');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo do revestimento lateral mala');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lente da lanterna do teto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro da cabine');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rele auxiliar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Friso da tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Chave de seta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Grampo da placa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Barra estabilizadora');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Barra estabilizadora suspensão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente borracha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente borracha amortecedor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente centragem direita tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente centragem esquerda tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente central');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente do amortecedor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente esquerdo porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente direito porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente fechadura');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente fechadura porta dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente fechadura porta traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente inferior porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente interno');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente regulagem de capo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente superior');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente suspensão traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Batente tampa traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bateria');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bico injetor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Biela completa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bocal reservatório');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Boia de combustível');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bolsa porta ferramenta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bolsa porta objetos');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bomba dagua');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bomba óleo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha arvore comando embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha arvore superior comando');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha cremalheira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha da barra');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha do amortecedor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha elastica cambio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha elastica suspensão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bucha tubo vareta nivel óleo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Bujão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cabecote motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa direcao mecanica');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa roda dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Caixa roda traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Calha vidro porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Came pedal embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Canaleta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa do retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa pedal acelerador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capa pedal freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Capota maritima');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Carter óleo motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cilindro embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coifa da alavanca');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coifa do amortecedor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Comando alavanca');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Comando buzina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Compressor do ar condicionado');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Comutador farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Conjunto pistões');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Correia alternador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Correia dentada');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Correia distribuição');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Correia poly v');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coxim');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coxim filtro ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Coxim suspensão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cubo roda dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Cubo roda traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Difusor ar painel');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Disco de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Elemento filtro de ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Espelho retrovisor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Espuma assento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Espuma encosto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Estrutura banco');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Estrutura encosto');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Farol neblina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fechadura capo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fechadura porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fechadura tampa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fecho cinto de segurança');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro anti polen');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro de ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro de combustível');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Filtro de óleo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 15a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 20a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 25a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 40a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 50a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 60a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Fusivel 70a');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor luz cortesia');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Interruptor vidro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo aneis para pistão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo cabo de velas');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo de tapetes');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo farol neblina');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo junta homocinética');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo juntas motor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo palhetas limpador parabrisa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo pastilhas freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Jogo tapetes borracha');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Junta coletor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit amortecedor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit coifa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit correia dentada');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit de embreagem');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Kit disco freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada 12v w16');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada da lanterna');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada da luz de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada do farol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada h1 12v');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada h4 55w');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada h7');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada h7 12v 55w');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada tubular 12v 10w');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampada w5w 12v');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lampejador dire');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Lanterna de freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Macaneta porta');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Macaneta tampa');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Mangueira tubo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Modulo air bag');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Mola suspensão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Óleo freio');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Para sol');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Parachoque');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Parachoque dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Parachoque traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Paralama');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Ponteira escapamento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Radiador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Radiador aquecimento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Radiador arrefecimento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento alternador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento cubo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento roda');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Rolamento tensor correia alternador');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor de fase');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor de giro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor de partida');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor de temperatura');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor do nivel');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor nivel de combustível');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Sensor pressao');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tubo tomada ar');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tubo vareta nivel');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tucho hidraulico');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Tucho valvula');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Turbocompressor');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Válvula');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Válvula admissão');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Válvula escapamento');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Válvula termostato');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vareta nivel óleo');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vela');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro lateral dianteiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro lateral traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro porta traseira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro porta dianteira');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro tampa traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro traseiro');
INSERT INTO maintenance_parts_list (part_name) VALUES ('Vidro traseiro corredico');